### ISSUE TITLE
Question about line of code

### ISSUE THREAD

**Issue by cjlovering** [yanaiela/amnesic_probing#3]
Hello,

I noticed a line where the return value isn't captured. I've run small experiments with toy data and it didn't seem to matter.

https://github.com/yanaiela/amnesic_probing/blob/36c2a1d01722b848066bb03d1d99e1fdf79c81e9/amnesic_probing/debias/debias.py#L26

Was the line unnecessary, or should it be:

```python
 w_basis = w_basis * np.sign(w_basis[0][0])  # handle sign ambiguity
```

**Comment by shauli-ravfogel** [comment]
Hi,

Scipy’s `orth` uses SVD, and there is an inherent sign ambiguity associated with SVD, see [here](https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/abs/10.1002/cem.1122). However, since the rowspace (and the projection onto it) is the same regardless of the sign of its basis vectors, we can safely remove this line from the code.

**Comment by cjlovering** [comment]
Thank you!
